version: "3.8"

services:
  madara:
    image: ghcr.io/keep-starknet-strange/madara:v0.1.0-testnet-sharingan-beta.7.1.experimental.4
    ports:
      - "9615:9615"
      - "9944:9944"
      - "30333:30333"
    command:
      - "--rpc-external"
      - "--rpc-methods=unsafe"
      - "--dev"
    networks:
      - checkpoint

  madara-app:
    image: ghcr.io/keep-starknet-strange/madara-app:latest
    ports:
      - "8080:80"
    environment:
      WS_URL: "ws://127.0.0.1:9944"
    networks:
      - checkpoint

  mysql:
    image: mysql:8.0
    container_name: checkpoint-mysql
    restart: always
    command:
      --default-authentication-plugin=mysql_native_password
    cap_add:
      - SYS_NICE
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=default_password
      - MYSQL_DATABASE=checkpoint
    volumes:
      - mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-pdefault_password"]
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - checkpoint

  checkpoint-template:
    image: ghcr.io/hel-kame/checkpoint-template:latest
    container_name: checkpoint-template
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./config.json:/usr/app/src/config.json
    restart: always
    ports:
      - "3000:3000"
    networks:
      - checkpoint

volumes:
  mysql:
    driver: local

networks:
  checkpoint:
