version: "3.2"

services:
  madara:
    image: ghcr.io/keep-starknet-strange/madara:latest
    ports:
      - "9615:9615"
      - "9944:9944"
      - "30333:30333"
    command:
      - "--rpc-external"
      - "--rpc-methods=unsafe"
      - "--dev"
    networks:
      - internal
    healthcheck:
      # This is a hack to just wait 5s
      # Need to improve this by calling, for example chainId
      test: echo "ok"
      interval: 5s

  # -------------
  # Substrate app
  # -------------
  madara-app:
    image: ghcr.io/keep-starknet-strange/madara-app:latest
    ports:
      - "8080:80"
    environment:
      WS_URL: "ws://127.0.0.1:9944"

  # --------
  # Starkcet
  # --------
  starkcet-front:
    image: ghcr.io/zizou0x/starkcet-frontend:latest
    ports:
      - 3001:3000
    depends_on:
      - starkcet-back
    networks:
      - internal

  starkcet-back:
    image: ghcr.io/zizou0x/starkcet-backend:latest
    environment:
      - PRIVATE_KEY=0x00c1cf1490de1352865301bb8705143f3ef938f97fdf892f1090dcb5ac7bcd1d
      - STARKNET_ACCOUNT_ADDRESS=0x2
      - TOKEN_ADDRESS=0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7
      - RPC_URL=http://madara:9944
      - AMOUNT_TRANSFERED=1000000000000000
    depends_on:
      madara:
        condition: service_healthy
    networks:
      - internal

  starksheet-deployer:
    image: ghcr.io/the-candy-shop/starksheet-monorepo/starksheet-cairo:latest
    depends_on:
      madara:
        condition: service_healthy
    environment:
      ACCOUNT_ADDRESS: "0x3"
      PRIVATE_KEY: "0x00c1cf1490de1352865301bb8705143f3ef938f97fdf892f1090dcb5ac7bcd1d"
      RPC_URL: http://madara:9944
    volumes:
      - starksheet-deployments:/app/starksheet/packages/starksheet-cairo/deployments
      - starksheet-build:/app/starksheet/packages/starksheet-cairo/build
    networks:
      - internal

  starksheet-webapp:
    image: ghcr.io/the-candy-shop/starksheet-monorepo/starksheet-webapp:latest
    depends_on:
      starksheet-deployer:
        condition: service_completed_successfully
    working_dir: /app/starksheet/packages/starksheet-webapp
    volumes:
      - starksheet-deployments:/app/starksheet/packages/starksheet-cairo/deployments/madara
      - starksheet-build:/app/starksheet/packages/starksheet-cairo/build
    environment:
      - REACT_APP_NETWORK=madara
      - REACT_APP_RPC_URL=http://0.0.0.0:9944
      - PORT=3003
    ports:
      - '3003:3003'
    networks:
      - internal

  # -------
  # Starken
  # -------
  starken-database:
    image: mongo:6-jammy
    ports:
      - 27017:27017
    volumes:
      - dbdata:/data/db

  starken-indexer:
    image: mathitchens/starken-madara-indexer:starken-madara-indexer
    depends_on:
      - starken-database
    environment:
      - MONGODB_URI=mongodb://starken-database:27017
      - PORT=5060
      - INDEXER=MADARA
      - API_ROUTE=https://api.coingecko.com/api/v3
      - APIBARA_KEY=dna_lK9j29Vfw1EzAWnk8nU1

  starken-api:
    image: mathitchens/starken-madara-api:starken-madara-api
    ports:
      - 5055:5055
    depends_on:
      - starken-database
      - starken-indexer
    environment:
      - MONGODB_URI=mongodb://starken-database:27017
      - PORT=5055

  starken-frontend:
    image: mathitchens/starken-madara-frontend:starken-madara-frontend
    ports:
      - 3002:3000
    depends_on:
      - starken-api
    environment:
      - NEXT_PUBLIC_FRONTEND_URL=http://localhost:3000
      - NEXT_PUBLIC_STARKEN_API_URL=http://localhost:5055

  # -------
  # Apibara
  # -------
# blocked while no arm64
#  apibara:
#    image: quay.io/apibara/starknet:7f00306001c1ff030ccc1babf49b880dbe6c7e0e
#    ports:
#      - 7171:7171
#    command:
#      - start
#    environment:
#      - RPC=http://madara:9944
#      - WAIT_FOR_RPC=true
#      - RUST_LOG=warn
#    restart: on-failure
#    depends_on:
#      madara:
#       condition: service_healthy
#    networks:
#      - internal

volumes:
  dbdata:
  starksheet-deployments:
  starksheet-build:
networks:
  internal:
